/// Flutter icons MeoMeoIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MeoMeoIcon
///      fonts:
///       - asset: fonts/MeoMeoIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MeoMeoIcon {
  MeoMeoIcon._();

  static const _kFontFam = 'MeoMeoIcon';
  static const String? _kFontPkg = null;

  static const IconData address = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
